# Generated by Django 4.1.4 on 2023-01-06 20:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelqueue
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiffusionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField()),
                ('filepath', models.FilePathField(blank=True, default=None, null=True, path=pathlib.PureWindowsPath('F:/projects/stable_diffusion/diffusion_gallery/gallery_models'), recursive=True)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('width', models.PositiveIntegerField(default=512, validators=[django.core.validators.MinValueValidator(64), django.core.validators.MaxValueValidator(4096), django.core.validators.StepValueValidator(64)])),
                ('height', models.PositiveIntegerField(default=512, validators=[django.core.validators.MinValueValidator(64), django.core.validators.MaxValueValidator(4096), django.core.validators.StepValueValidator(64)])),
                ('text', models.TextField(max_length=1000)),
                ('steps', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('seed', models.CharField(max_length=16)),
                ('sampler', models.CharField(choices=[('euler', 'Euler'), ('heun', 'Heun'), ('lms', 'LMS'), ('plms', 'PLMS'), ('ddim', 'DDIM'), ('dpm2', 'DPM2'), ('euler_a', 'Euler Ancestral'), ('dpm2_a', 'DPM2 Ancestral')], default='euler', max_length=16)),
                ('batch_size', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('scale', models.FloatField(default=7.5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50), django.core.validators.StepValueValidator(0.1)])),
                ('eta', models.FloatField(default=0.01, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1), django.core.validators.StepValueValidator(0.01)])),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery.diffusionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BigIntegerField(db_index=True, default=modelqueue.Status.waiting)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.prompt')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='images/generated/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery.prompt')),
            ],
        ),
    ]
